### ISSUE TITLE
フォントの埋め込み

### ISSUE THREAD

**Issue by oyamad** [yuichirotsuji/envelopetheorem#2]
dvipdfmx でフォントを埋め込むように設定する件ですが，
ここに書いてあるのはどうですか：
http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeXworks#aa8923ee

もし解決したら，
状況説明と問題点，その解決方法をゼミの wiki ページに書いてみんなとシェアしてください．

**Comment by yuichirotsuji** [comment]
この方法を試したところ、上手くいきました！
wikiに書いておこうと思います。
